### PR TITLE
Filter deserialization now maintains NotFilter toplevelness

### PR DESCRIPTION
**Pull request by philipcarlsen**
This pull request is a proposal to fix issue #7.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Have you tested this to see that it solves the original problem?

Can we put in some sort of unit test?

**Comment by philipcarlsen** [comment]
I tested it in a debugging session and verified that indeed the runner now skips explicit tests when given a not-filter.

I also gave testing a bit of thought, but were at a loss at deciding what would make a good test. I mean, it's easy to just make the "CreateV2Filter" method public and test that not-filters at the toplevel have TopLevel = true, and perhaps conversely, that not-toplevel ones have TopLevel = false, but I'm wondering if that's really the test we'd like to have, as what we're really interested in is the effect that the runner skips explicit tests (that would have otherwise matched the filter). But that's really more of an integration test, and looking at the nunit-v2-framework.tests project I couldn't determine whether that would be considered a good fit.

Maybe I'm just overthinking it or still a little disoriented from having to familiarize myself with a new codebase.

Alternatively, perhaps a nice test would be to assert that a not-filter `f` constructed with CreateV2Filter has `f.Pass(t) =false` where `t.RunState ==Runstate.Explicit`?

**Comment by CharliePoole** [comment]
The tests in NUnit2FrameworkDriverTests are not unit tests, but that's OK. Just add one that does a run with a filter. The test assembly has a category "Generics", so all you need to do is run with a filter based on category != "Generics". You will have to create the filter XML manually. Add an Explicit attribute to one of the non-generic classes and verify that the count of test cases is as expected.

**Comment by CharliePoole** [comment]
Fixes #7 

@philipcarlsen The above will get the issue automatically closed when we merge this issue to master. "Fix #7" will also work. We generally put this in our description, so you know for any future PRs.

**Comment by philipcarlsen** [comment]
Great, thanks for the feedback @CharliePoole.

**Comment by philipcarlsen** [comment]
... And now with tests as well :-)

However, I was actually surprised to find that there was a an observable difference between (A)

    [TestFixture]
    [Category("C")]
    class TestA
    {
      [Test]
      [Explicit]
      void ExplicitTest() { }
    }

and (B)

    [TestFixture]
    class TestA
    {
      [Test]
      [Category("C")]
      [Explicit]
      void ExplicitTest() { }
    }

in that filtering on category `"C"` in (A) *did not* match `TestExplicit`, while filtering on category `"C"` in (B) *did* match `TestExplicit`.

This means that the statement "`TestExplicit` belongs to category `"C"`" is insufficient to reason whether or not it will run when filtered by category.

This behavior appears to be intentional though (as evidenced in `TestFilter.MatchParent()`), and while surely there will be no more releases of nunit-v2, I couldn't help but voice my opinion, as I feel that it's important to be able to reason about the programs we write and the systems we use :-)

**Comment by CharliePoole** [comment]
Looks good to me. Thanks for your work!

Regarding your comment about Explicit... it is of course possible to reason about Explicit, otherwise I wouldn't have been able to write the code!

I think the confusion is because you are viewing the test in example A as somehow "inheriting" the category. That's not the case, although in some cases it's possible to think of it that way and still come up with the right answer. Strictly speaking, however, only the test (fixture in case A) actually marked with the CategoryAttribute is in that category and only that test is explicitly selected by using the category. You can think of Explicit as meaning "Doesn't run merely because it's container ran."

That has actually been the meaning of Explicit since shortly after we introduced it. The original Explicit (in a beta release) was a property on the CategoryAttribute, but we quickly discovered that it had use entirely apart from categories. That separation made it a bit more complex, however, and it continues ot confuse people today!

**Pull request merged**
