### PR TITLE
Include Repository URL in NuGet packaging, and update Cake Build

### PR DESCRIPTION
**Pull request by MaximRouiller**
This is the basic change to have the Source Code link in the NuGet gallery.

### CODE REVIEW

**Comment by MaximRouiller** [comment]
Can someone test that one out? I don't have cake but from what I understood out of the docs... it's what is required to build it.

**Comment by MaximRouiller** [comment]
From the error I see, the cake version must not be up to date. 😢

**Comment by MaximRouiller** [comment]
And the build seems to work. Enjoy. 😄

**Review by jnm2 — APPROVED** [review]

**Review by mikkelbu — APPROVED** [review]

**Comment by ChrisMaddock** [comment]
Awesome - thanks for contributing all these @MaximRouiller! 

(@mikkelbu - do you not have access to merge these? I think you should do!)

**Comment by mikkelbu** [comment]
@ChrisMaddock Nope 😄. I did not have the rights to do a merge, but I also remember that we once had differences in rights (see https://github.com/nunit/nunit/pull/2489#issuecomment-336892033), but the issue was never investigated AFAIK.

**Comment by ChrisMaddock** [comment]
@mikkelbu - I think this one may be a simpler problem to the previous one - I've posted https://github.com/orgs/nunit/teams/engine-team/discussions/3 😄

**Pull request merged**
