### PR TITLE
Convert NUnit 3 ID filter to V2

### LINKED ISSUE #29: V2 Driver does not support id filters
This doesn't impact the console runner or VS adapter, which don't use id filters. In a GUI, they are the most natural thing to use. 

If the GUI knew when it was running V2 tests, it could pass a different filter. However, it doesn't know that and we wouldn't want each runner to have to deal with this separately.

The problem is exacerbated by the fact that the exception generated is swallowed whole by `MasterTestRunner`, which uses a `when` clause to only handle certain exceptions. Other exceptions are allowed to continue. That would be OK except that the method where this happens is run on a worker thread so the exception goes unhandled.

I'll fix this by first handling the exception and reporting it. Beyond that, we need to decide if the engine should do a filter conversion or the V2 driver should do it. Currently, the V2 driver converts other filters, but not the id filter.

It would also be possible to upgrade the legacy V2 code to directly handle id filters, in which case that feature could be used by a new release of the V2 driver.

I'm assigning this to myself for the purpose of at least reporting the exception. Some discussion on how to take it further is needed to take the next steps.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #29

### CODE REVIEW

**Comment by CharliePoole** [comment]
@ChrisMaddock I literally forgot that this project was part of NUnit as I was jumping back and forth between nunit-legacy and TestCentric. Anyway, I merged it without review. Can you take a look and tell me whether you'd like leave it, back it out or make further forward changes?

**Comment by CharliePoole** [comment]
@ChrisMaddock I noticed that this is still building as 3.7.0-dev-xxxx rather than 3.7.1. I'll do another PR just for that.

**Comment by CharliePoole** [comment]
@ChrisMaddock If you aren't the person to decide about this, please let me know. I actually don't know who is these days and we can have a core-team discussion about it if necessary. See my comment on #27.

**Comment by mikkelbu** [comment]
I can probably review it tonight, but I don't know who is responsible for this project (I have only followed this repo for a couple of months)

**Comment by CharliePoole** [comment]
@mikkelbu That would help in any case. But of course the change is of no use without a release, so that's why I'd like to know who's responsible.

**Comment by ChrisMaddock** [comment]
Hi @CharliePoole. I have no intention in being responsible for these projects I'm afraid, I lack the v2 knowledge to do so.

You'll remember this was something we discussed a while ago. I re-started the wider discussion on that here: https://github.com/orgs/nunit/teams/core-team/discussions/18

**Comment by CharliePoole** [comment]
Hi @ChrisMaddock. Thanks for the clarification.

I do remember the discussion. I thought we ended up with the decision that all extensions, except for TeamCity, would be treated as part of the engine project. That's why I was bugging you about it.

Somewhere in the discussion you started, I hope you'll state what you do feel responsible for. For example, what about the other (non-V2) extensions?

I'll continue in that discussion.

**Comment by CharliePoole** [comment]
As for this merged PR, since there is nobody currently responsible to ask me to back it out or to specify the rules of engagement for merges, I'm going to move ahead and leave it in. :smiley_cat:

**Pull request merged**
